name: Chromatic
on: push
jobs:
  chromatic:
    name: "Chromatic - ${{ matrix.workingDir }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - workingDir: "./apps/storybook"
            projectToken: CHROMATIC_PROJECT_TOKEN_APPS_SB
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Required to retrieve git history
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run Chromatic
        uses: chromaui/action@v11
        with:
          workingDir: ${{ matrix.workingDir }}
          buildScriptName: storybook:build
          projectToken: ${{ secrets[matrix.projectToken] }}
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyChanged: true
          zip: true
          skip: "dependabot/**"
