name: Docker Image CI (Preview/Development)

# Events that trigger workflows
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  workflow_dispatch: # Manual triggers only
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        default: "0"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write

jobs:
  ###########################################################
  # Create a tag for the Docker image
  ###########################################################
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Set new tag as output
        id: tag_version
        run: |
          if [[ -z "$PR_NUMBER" || "$PR_NUMBER" -eq 0 ]]; then
            echo "NEW_TAG=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "NEW_TAG=pr-${PR_NUMBER}" >> $GITHUB_OUTPUT
          fi
        env:
          PR_NUMBER: ${{ github.event.inputs.pr_number }}

  ###########################################################
  # Build Docker image
  ###########################################################
  build_image:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      test_image_name: "rayo-web:test"
      vercel_git_commit_ref: "${{ github.ref_name }}"
      enable_redis_cache: true
    secrets:
      next_public_sentry_dsn: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
      sentry_org: ${{ secrets.SENTRY_ORG }}
      sentry_project: ${{ secrets.SENTRY_PROJECT }}
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}

  ###########################################################
  # Scan Docker image with Wiz
  ###########################################################
  scan_image:
    needs: build_image
    uses: ./.github/workflows/scan-docker-image.yml
    with:
      test_image_name: "rayo-web:test"
      wiz_scanning_policy: "Default vulnerabilities policy"
    secrets:
      uk_audio_wiz_client_id: ${{ secrets.UK_AUDIO_WIZ_CLIENT_ID }}
      uk_audio_wiz_client_secret: ${{ secrets.UK_AUDIO_WIZ_CLIENT_SECRET }}

  ###########################################################
  # Push to GitHub Container Registry
  ###########################################################
  publish_to_ghcr:
    needs: [create_tag, build_image]
    uses: ./.github/workflows/publish-ghcr.yml
    with:
      test_image_name: "rayo-web:test"
      github_repository: ${{ github.repository }}
      docker_tag: ${{ needs.create_tag.outputs.docker_tag }}

  ###########################################################
  # Push to AWS ECR
  ###########################################################
  publish_to_ecr:
    needs: [create_tag, build_image]
    uses: ./.github/workflows/publish-ecr.yml
    with:
      test_image_name: "rayo-web:test"
      aws_account_id: "800508964711"
      aws_region: "eu-west-2"
      github_repository: ${{ github.repository }}
      docker_tag: ${{ needs.create_tag.outputs.docker_tag }}

  ###########################################################
  # Trigger Helm Chart update
  ###########################################################
  trigger_helm_chart:
    needs: [create_tag, publish_to_ecr, publish_to_ghcr]
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: autoupdate.yml
          token: "${{ secrets.HELMCHARTS_ACTIONS_ACCESS_TOKEN }}"
          inputs: '{ "version": "${{ needs.create_tag.outputs.docker_tag }}", "chart_name": "helix-web", "version_fragment": "pre" }'
          repo: BauerXcel/uk-audio-services-helm-charts
          ref: "main"
