name: Publish to GitHub Container Registry

on:
  workflow_call:
    inputs:
      test_image_name:
        required: true
        type: string
      github_repository:
        required: true
        type: string
      docker_tag:
        required: true
        type: string

jobs:
  publish_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
      - name: Load Docker image from tarball
        run: docker load < image.tar
      - name: Create image names
        run: |
          IMAGE_NAME=$(echo "${{ inputs.github_repository }}" | tr '[:upper:]' '[:lower:]'):${{ inputs.docker_tag }}
          GHCR_IMAGE_NAME=ghcr.io/$IMAGE_NAME
          echo "GHCR_IMAGE_NAME=$GHCR_IMAGE_NAME" >> "$GITHUB_ENV"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Container Registry
        run: |
          docker tag ${{ inputs.test_image_name }} ${{ env.GHCR_IMAGE_NAME }}
          docker push ${{ env.GHCR_IMAGE_NAME }}
